### PR TITLE
Smash Magazine heatmap page

### PR DESCRIPTION
**Pull request by vmwhoami**
We created a grayscale heat map of the Smash Magazine website that indicates which elements have the greatest weight in the visual hierarchy.

We made use of floats, grid and position.

### CODE REVIEW

**Comment by rammazzoti2000** [comment]
## Pull Request under review byAlexandru Bangau (TSE)

**Comment by rammazzoti2000** [comment]
## Project Approved :rocket: :tada: 
Hello team great job, your project is approved, feel free to merge whenever you are ready.
###
Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :heavy_check_mark: Status: Approved

**Review by rammazzoti2000 — APPROVED** [review]
## Project Approved :rocket: :tada: 
Hello team great job, your project is approved, feel free to merge whenever you are ready.

###
Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :heavy_check_mark: Status: Approved

**Comment by acushlakoncept** [comment]
> ## Project Approved 🚀 🎉
> Hello team great job, your project is approved, feel free to merge whenever you are ready.
> 
> Cheers and Happy coding! 👏
> 
> ##### Code review by Alexandru Bangau
> (Feel free to contact me on slack by the handle of alexandru if you have any additional question)
> 
> ### ✔️ Status: Approved

Thank you @rammazzoti2000

**Pull request merged**
